name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update apt
      run: sudo apt-get -y update
    - name: install packages
      run: sudo apt-get install libgtk-3-dev build-essential checkinstall gfortran
    - name: install OpenGL libraries
      run: sudo apt-get install mesa-utils
    - name: install freeGlut
      run: sudo apt-get install freeglut3-dev
    - name: install mathgl
      run: sudo apt-get install mathgl libmgl-dev
    - name: install lapack
      run: sudo apt-get install liblapack3 liblapack-dev libopenblas-base libopenblas-dev liblapack-dev liblapacke-dev
    - name: extract WX
      run: tar -xvjf wxWidgets-3.0.5.tar.bz2
    - name: create WXBuildDIR
      working-directory: wxWidgets-3.0.5
      run: mkdir gtk-build
    - name: configure WX
      working-directory: wxWidgets-3.0.5/gtk-build
      run: ../configure --enable-unicode --with-opengl --with-libpng
    - name: compile WX
      working-directory: wxWidgets-3.0.5/gtk-build
      run: make
    - name: install WX
      working-directory: wxWidgets-3.0.5/gtk-build
      run: sudo make install
    - name: set RapidXML DIR
      run: echo "RapidXML_DIR=${GITHUB_WORKSPACE}/rapidxml-1.13" >> $GITHUB_ENV
    - name: set PATH
      run: echo "PATH=/usr/local/include/wx-3.0:$PATH" >> $GITHUB_ENV
    - name: compile tbstudio
      run: make -e
