name: TBStudio CI-CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build-macos-11:

    runs-on: macos-11
    
    steps:
    - uses: actions/checkout@v1
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: update
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install openblas
        brew install lapack
        port install mathgl
    - name: extract WX
      run: tar -xvjf wxWidgets-3.0.5.tar.bz2
    - name: compile WX
      run: |
        ../configure --enable-unicode --with-opengl --with-libpng --with-macosx-version-min=10.11
        make
        sudo make install
        sudo update_dyld_shared_cache
      
