name: TBStudio CI-CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build-macos-11:

    runs-on: macos-11
    
    steps:
    - uses: actions/checkout@v1
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: install package managers
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        wget https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-11-BigSur.pkg
        sudo installer -pkg ./MacPorts-2.7.1-11-BigSur.pkg -target /
    - name: set PATH
      run: echo "/opt/local/bin" >> $GITHUB_PATH
    - name: install packages
      run: sudo port install mathgl
#     - name: extract WX
#       run: tar -xvjf wxWidgets-3.0.5.tar.bz2
#     - name: create WXBuildDIR
#       working-directory: wxWidgets-3.0.5
#       run: mkdir gtk-build
#     - name: compile WX
#       working-directory: wxWidgets-3.0.5/gtk-build
#       run: |
#         ../configure --enable-unicode --with-opengl --with-libpng --with-macosx-version-min=10.11
#         make
#         sudo make install
#         sudo update_dyld_shared_cache
    - name: install packages
      run: ls /usr/local/opt/lapack
