name: TBStudio CI-CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build-windows-latest:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: suisei-cn/actions-download-file@v1
      id: wxconfigid
      name: Download the file
      with:
        url: "https://dl.dropboxusercontent.com/s/jrxjmnuoav3t0vj/wxconfig.7z?dl=0"
        target: windowsDeps/
    - uses: suisei-cn/actions-download-file@v1
      id: freeglut64id
      name: Download the file
      with:
        url: "https://dl.dropboxusercontent.com/s/drapc4swnga1285/freeglut64.7z?dl=0"
        target: windowsDeps/
    - uses: suisei-cn/actions-download-file@v1
      id: fortranid
      name: Download the file
      with:
        url: "https://dl.dropboxusercontent.com/s/lrj3g2w564d0mok/gcc-5.1.0-tdm64-1-fortran.7z?dl=0"
        target: windowsDeps/
    - uses: suisei-cn/actions-download-file@v1
      id: gemmiid
      name: Download the file
      with:
        url: "https://dl.dropboxusercontent.com/s/zym925kz2yvrlr5/gemmi-master.7z?dl=0"
        target: windowsDeps/
    - uses: suisei-cn/actions-download-file@v1
      id: lapackid
      name: Download the file
      with:
        url: "https://dl.dropboxusercontent.com/s/u7vnxn77a87i9le/LAPACKE-X64.7z?dl=0"
        target: windowsDeps/
    - uses: suisei-cn/actions-download-file@v1
      id: mathglid
      name: Download the file
      with:
        url: "https://dl.dropboxusercontent.com/s/7u841sclxxjztmf/MathGL32LGPL.7z?dl=0"
        target: windowsDeps/
    - uses: suisei-cn/actions-download-file@v1
      id: tdmgccid
      name: Download the file
      with:
        url: "https://dl.dropboxusercontent.com/s/siy11m4rxo1oj2t/TDM-GCC-64.7z?dl=0"
        target: windowsDeps/
    - uses: suisei-cn/actions-download-file@v1
      id: wxwidgetid
      name: Download the file
      with:
        url: "https://dl.dropboxusercontent.com/s/uoh7y7b296mf1lj/wxWidgets-3.1.1.7z?dl=0"
        target: windowsDeps/
    - name: dir
      working-directory: windowsDeps
      run: dir
    - name: unzip dependencies
      working-directory: windowsDeps
      run: |
        ..\7zip\32\7z.exe x .\wxconfig.7z
        ..\7zip\32\7z.exe x .\freeglut64.7z
        ..\7zip\32\7z.exe x .\gemmi-master.7z
        ..\7zip\32\7z.exe x .\LAPACKE-X64.7z
        ..\7zip\32\7z.exe x .\MathGL32LGPL.7z
        ..\7zip\32\7z.exe x .\TDM-GCC-64.7z
        ..\7zip\32\7z.exe x .\wxWidgets-3.1.1.7z
    - name: unzip dependencies
      working-directory: windowsDeps\TDM-GCC-64
      run: |
        move ..\gcc-5.1.0-tdm64-1-fortran.7z .\gcc-5.1.0-tdm64-1-fortran.7z
        ..\..\7zip\32\7z.exe x .\gcc-5.1.0-tdm64-1-fortran.7z
    - name: dir
      working-directory: windowsDeps
      run: dir
    - name: set wxconfig DIR
      run: echo "wxconfigDir=${GITHUB_WORKSPACE}\windowsDeps\wxconfig" >> $env:GITHUB_ENV
    - name: set RapidXML DIR
      run: echo "RapidXML_DIR=${GITHUB_WORKSPACE}\windowsDeps\rapidxml-1.13" >> $env:GITHUB_ENV
    - name: set WXWIN
      run: echo "WXWIN=${GITHUB_WORKSPACE}\windowsDeps\wxWidgets-3.1.1" >> $env:GITHUB_ENV
    - name: set TDM-GCC-64
      run: echo "GCC_DIR=${GITHUB_WORKSPACE}\windowsDeps\TDM-GCC-64" >> $env:GITHUB_ENV
    - name: set GFORTRAN_DIR
      run: echo "GFORTRAN_DIR=${GITHUB_WORKSPACE}\windowsDeps\TDM-GCC-64\gcc-5.1.0-tdm64-1-fortran" >> $env:GITHUB_ENV
    - name: set WXCFG
      run: echo "WXCFG=gcc_dll\mswu" >> $env:GITHUB_ENV
    - name: set Opengl_DIR
      run: echo "Opengl_DIR=${GITHUB_WORKSPACE}\windowsDeps\TDM-GCC-64\x86_64-w64-mingw32\lib" >> $env:GITHUB_ENV
    - name: set MathGL_DIR
      run: echo "MathGL_DIR=${GITHUB_WORKSPACE}\windowsDeps\MathGL64LGPL" >> $env:GITHUB_ENV
    - name: set LAPACKE_DIR
      run: echo "LAPACKE_DIR=${GITHUB_WORKSPACE}\windowsDeps\LAPACKE-X64" >> $env:GITHUB_ENV
    - name: set Glut_DIR
      run: echo "Glut_DIR=${GITHUB_WORKSPACE}\windowsDeps\freeglut64" >> $env:GITHUB_ENV
    - name: set Gemmi_DIR
      run: echo "Gemmi_DIR=${GITHUB_WORKSPACE}\windowsDeps\gemmi-master" >> $env:GITHUB_ENV
    - name: set path1
      run: echo "PATH=%wxconfigDir%;%PATH%" >> $env:GITHUB_ENV
    - name: set path2
      run: echo "PATH=%WXWIN%\lib\gcc_dll;%GCC_DIR%\bin;%PATH%" >> $env:GITHUB_ENV
    - name: set path3
      run: echo "PATH=%MathGL_DIR%\bin;%PATH%" >> $env:GITHUB_ENV
    - name: set path4
      run: echo "PATH=%Glut_DIR%\bin;%PATH%" >> $env:GITHUB_ENV
    - name: set path5
      run: echo "PATH=%LAPACKE_DIR%;%PATH%" >> $env:GITHUB_ENV
    - name: set path6
      run: echo "PATH=%GFORTRAN_DIR%\bin;%PATH%" >> $env:GITHUB_ENV
    - name: copy Windows Makefile
      run: cp .\GUI\WindowsGUI.mk .\GUI\GUI.mk
    - name: compile tbstudio
      run: |
        mingw32-make -e
    - name: dir
      working-directory: GUI\Release
      run: dir
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: .\GUI\Release\tbstudio.exe
